services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001" # Maps container port 5001 to localhost
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: san16
      MYSQL_DB: userdb
    depends_on:
      - db
    volumes:
      - .:/app # Mounts your project directory in the container
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: san16
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3306" # Maps MySQL port 3306
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
